[phases.setup]
nixPkgs = ["nodejs_22", "python312", "gcc", "ffmpeg"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "node build.mjs",
  "python3 -m venv .venv",
  ".venv/bin/pip install --upgrade pip",
  ".venv/bin/pip install yt-dlp pyrogram tgcrypto py-tgcalls"
]

[start]
cmd = "node dist/index.mjs"
